### ISSUE TITLE
NEST: Spikes get lost in the first few ms

### ISSUE THREAD

**Issue by costrau** [hbp-unibi/cypress#1]
If you select NEST as simulator, all spikes in the first few ms are suppressed. You can check this behaviour by simply shifting the same simulation by e.g. 100ms.
This is probably due to wrong initialisation of the membrane voltages at the beginning of the simulation.

**Comment by astoeckel** [comment]
Fixed by commits f7e2eac2870e4ca491db450abc46bf5e7093a801 and 6593dff80d375c3409025e6ac485cf2a3be4682a
